apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-template-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-template
  template:
    metadata:
      labels:
        app: fastapi-template
    spec:
      containers:
        - image: 'alexeyn00000/fastapi-template:latest'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          name: fastapi-template
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 256m
              memory: 256Mi
              ephemeral-storage: 128Mi
            requests:
              cpu: 256m
              memory: 256Mi
              ephemeral-storage: 128Mi
            volumeMounts:
            - name: settings
              mountPath: "/app/conf"
              readOnly: true
      volumes:
      - name: settings
        secret:
          secretName: fastapi-template-settings
          optional: false             

