name: Build and publish Docker image
on:
  push:
    branches:
      - main
    paths:
      - app/*
      - libs/*
      - requirements.txt
      - Dockerfile
      - .github/workflows/*.yml

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t alexeyn00000/fastapi-template:latest .
      - name: Push Docker image
        run: docker push alexeyn00000/fastapi-template:latest
