name: CICD pipeline
on:
  push:
    branches:
      - main
    paths:
      - app/*
      - libs/*   
      - .github/workflows/*.yml
      - requirements.txt
      - Dockerfile
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=512 --statistics --ignore=E501,E402,E124
    - name: Test with pytest
      run: |
        export PYTHONPATH="${PYTHONPATH}:." && pytest -s -v tests/test*.py

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t alexeyn00000/fastapi-template:latest .
      - name: Push Docker image
        run: docker push alexeyn00000/fastapi-template:latest